name: Promote Agent Definition

on:
  workflow_dispatch:
    inputs:
      conflict_resolution_strategy:
        description: 'Conflict Resolution Strategy'
        required: false
        default: 'SkipConflictingEntities'
        type: choice
        options:
          - SkipConflictingEntities
          - OverwriteConflictingEntities
      default_project_behavior:
        description: 'Default Project Behavior'
        required: false
        default: 'Library'
        type: choice
        options:
          - Library
          - Project
      run_evaluation:
        description: 'Run automated evaluation after promotion'
        required: false
        default: true
        type: boolean

jobs:
  promote-agent:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check if pipelineDefinition.json exists
        run: |
          if [ ! -f "pipelineDefinition.json" ]; then
            echo "Error: pipelineDefinition.json not found in repository root"
            exit 1
          fi
          
      - name: Generate correlation ID
        id: correlation
        run: echo "correlation_id=$(uuidgen)" >> $GITHUB_OUTPUT
        
      - name: Promote agent to Airia
        id: promote
        run: |
          # Read the pipeline definition
          echo "Reading pipelineDefinition.json..."
          if [ ! -f "pipelineDefinition.json" ]; then
            echo "Error: pipelineDefinition.json not found"
            exit 1
          fi
          
          pipeline_definition=$(cat pipelineDefinition.json)
          echo "Pipeline definition loaded successfully"
          
          # Set default values for non-workflow_dispatch triggers
          conflict_strategy="${{ github.event.inputs.conflict_resolution_strategy || 'SkipConflictingEntities' }}"
          project_behavior="${{ github.event.inputs.default_project_behavior || 'Library' }}"
          
          echo "Using conflict strategy: $conflict_strategy"
          echo "Using project behavior: $project_behavior"
          
          # Validate JSON before processing
          echo "$pipeline_definition" | jq . > /dev/null
          if [ $? -ne 0 ]; then
            echo "Error: Invalid JSON in pipelineDefinition.json"
            exit 1
          fi
          
          # Create the request payload
          echo "Creating request payload..."
          # Show what parameters we have available
          echo "Available parameters:"
          echo "  projectId: ${{ secrets.AIRIA_PROJECT_ID }}"
          echo "  tenantId: ${{ secrets.AIRIA_TENANT_ID }}"
          echo "  userId: ${{ secrets.AIRIA_USER_ID }}"
          echo "  organizationId: ${{ secrets.AIRIA_ORGANIZATION_ID }}"
          echo "  workspaceId: ${{ secrets.AIRIA_WORKSPACE_ID }}"
          echo "  conflictResolutionStrategy: $conflict_strategy"
          echo "  defaultProjectBehavior: $project_behavior"
          
          payload=$(jq -n \
            --argjson pipelineDefinition "$pipeline_definition" \
            --arg projectId "${{ secrets.AIRIA_PROJECT_ID }}" \
            --arg tenantId "${{ secrets.AIRIA_TENANT_ID }}" \
            --arg userId "${{ secrets.AIRIA_USER_ID }}" \
            --arg organizationId "${{ secrets.AIRIA_ORGANIZATION_ID }}" \
            --arg workspaceId "${{ secrets.AIRIA_WORKSPACE_ID }}" \
            --arg clientId "${{ secrets.AIRIA_CLIENT_ID }}" \
            --arg environmentId "${{ secrets.AIRIA_ENVIRONMENT_ID }}" \
            --arg conflictResolutionStrategy "$conflict_strategy" \
            --arg defaultProjectBehavior "$project_behavior" \
            '{
              pipelineDefinition: $pipelineDefinition,
              projectId: (if $projectId == "" then null else $projectId end),
              tenantId: (if $tenantId == "" then null else $tenantId end),
              userId: (if $userId == "" then null else $userId end),
              organizationId: (if $organizationId == "" then null else $organizationId end),
              workspaceId: (if $workspaceId == "" then null else $workspaceId end),
              clientId: (if $clientId == "" then null else $clientId end),
              environmentId: (if $environmentId == "" then null else $environmentId end),
              conflictResolutionStrategy: $conflictResolutionStrategy,
              defaultProjectBehavior: $defaultProjectBehavior
            }')
          
          if [ $? -ne 0 ]; then
            echo "Error: Failed to create JSON payload"
            exit 1
          fi
          
          echo "Payload created successfully"
          
          # Determine the API endpoint
          api_endpoint="${AIRIA_API_ENDPOINT:-https://prodaus.api.airia.ai/v1/PipelineImport}"
          echo "API Endpoint: $api_endpoint"
          
          # Test DNS resolution
          hostname=$(echo "$api_endpoint" | sed 's|https\?://||' | sed 's|/.*||')
          echo "Testing DNS resolution for: $hostname"
          nslookup "$hostname" || echo "DNS resolution failed for $hostname"
          
          # Check if API token is provided
          if [ -z "${{ secrets.AIRIA_API_TOKEN }}" ]; then
            echo "Error: AIRIA_API_TOKEN secret is not set"
            exit 1
          fi
          
          # Use the API token (format appears correct from previous debugging)
          api_token="${{ secrets.AIRIA_API_TOKEN }}"
          echo "Token length: ${#api_token}"
          echo "Token format: ${api_token:0:10}...${api_token: -10}"
          
          # Make the API call
          echo "Making API call..."
          echo "Correlation ID: ${{ steps.correlation.outputs.correlation_id }}"
          echo "Request headers:"
          echo "  x-correlation-id: ${{ steps.correlation.outputs.correlation_id }}"
          echo "  Content-Type: application/json"
          echo "  Accept: application/json"
          echo "  Authorization: Bearer [REDACTED]"
          echo "  X-API-Key: [REDACTED]"
          echo "  X-Tenant-ID: ${{ secrets.AIRIA_TENANT_ID }}"
          echo "  X-User-ID: ${{ secrets.AIRIA_USER_ID }}"
          echo "  X-Organization-ID: ${{ secrets.AIRIA_ORGANIZATION_ID }}"
          echo "  X-Workspace-ID: ${{ secrets.AIRIA_WORKSPACE_ID }}"
          echo "  X-Client-ID: ${{ secrets.AIRIA_CLIENT_ID }}"
          echo "  X-API-Version: v1"
          echo "  User-Agent: GitHub-Actions-Airia-Agent-Promotion/1.0"
          
          echo "Request payload structure:"
          echo "$payload" | jq -C '.' || echo "Failed to format payload as JSON"
          
          set +e  # Temporarily disable exit on error
          response=$(curl -s -w "\n%{http_code}" -X POST \
            -H "x-correlation-id: ${{ steps.correlation.outputs.correlation_id }}" \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $api_token" \
            -H "X-API-Key: $api_token" \
            -H "X-Tenant-ID: ${{ secrets.AIRIA_TENANT_ID }}" \
            -H "X-User-ID: ${{ secrets.AIRIA_USER_ID }}" \
            -H "X-Organization-ID: ${{ secrets.AIRIA_ORGANIZATION_ID }}" \
            -H "X-Workspace-ID: ${{ secrets.AIRIA_WORKSPACE_ID }}" \
            -H "X-Client-ID: ${{ secrets.AIRIA_CLIENT_ID }}" \
            -H "X-API-Version: v1" \
            -H "User-Agent: GitHub-Actions-Airia-Agent-Promotion/1.0" \
            -d "$payload" \
            "$api_endpoint")
          curl_exit_code=$?
          set -e  # Re-enable exit on error
          echo "Curl exit code: $curl_exit_code"
          
          if [ $curl_exit_code -ne 0 ]; then
            echo "Error: curl command failed with exit code $curl_exit_code"
            case $curl_exit_code in
              6) echo "Couldn't resolve host. DNS problem?" ;;
              7) echo "Failed to connect to host" ;;
              28) echo "Operation timeout" ;;
              *) echo "Unknown curl error" ;;
            esac
            exit 1
          fi
          
          # Extract response body and status code
          response_body=$(echo "$response" | head -n -1)
          status_code=$(echo "$response" | tail -n 1)
          
          echo "Status Code: $status_code"
          echo "Response: $response_body"
          
          # Check if the request was successful
          if [ "$status_code" -ge 200 ] && [ "$status_code" -lt 300 ]; then
            echo "✅ Agent definition promoted successfully!"
            echo "Correlation ID: ${{ steps.correlation.outputs.correlation_id }}"
            
            # Extract agent version ID from response for evaluation
            agent_version_id=$(echo "$response_body" | jq -r '.agentVersionId // .id // empty')
            if [ -n "$agent_version_id" ]; then
              echo "agent_version_id=$agent_version_id" >> $GITHUB_OUTPUT
              echo "Agent Version ID: $agent_version_id"
            fi
          else
            echo "❌ Failed to promote agent definition"
            echo "Status Code: $status_code"
            echo "Response: $response_body"
            
            # Provide specific guidance for common error codes
            case $status_code in
              401) echo "Authentication failed. Please check your AIRIA_API_TOKEN secret." ;;
              403) echo "Access forbidden. Token may not have required permissions." ;;
              404) echo "Endpoint not found. Please check the API endpoint URL." ;;
              422) echo "Invalid request payload. Check your pipelineDefinition.json format." ;;
              500) echo "Server error. Please try again later." ;;
            esac
            exit 1
          fi
        env:
          AIRIA_API_ENDPOINT: ${{ secrets.AIRIA_API_ENDPOINT }}
          
      - name: Run Agent Evaluation
        if: ${{ (github.event.inputs.run_evaluation != 'false' || github.event.inputs.run_evaluation == null) && steps.promote.outputs.agent_version_id }}
        run: |
          echo "🧪 Starting automated agent evaluation..."
          
          # Generate new correlation ID for evaluation
          eval_correlation_id=$(uuidgen)
          echo "Evaluation Correlation ID: $eval_correlation_id"
          
          # Create evaluation request
          response=$(curl -s -w "\n%{http_code}" \
            -X POST \
            -H "x-correlation-id: $eval_correlation_id" \
            -H "Authorization: Bearer ${{ secrets.AIRIA_API_TOKEN }}" \
            -F "AgentVersionIds=${{ steps.promote.outputs.agent_version_id }}" \
            -F "ModelId=${{ secrets.AIRIA_EVALUATION_MODEL_ID }}" \
            -F "ExternalAgents=" \
            "${AIRIA_EVALUATION_ENDPOINT:-https://prodaus.api.airia.ai/v1/AgentEvaluation}")
          
          # Extract response body and status code
          response_body=$(echo "$response" | head -n -1)
          status_code=$(echo "$response" | tail -n 1)
          
          echo "Evaluation Status Code: $status_code"
          echo "Evaluation Response: $response_body"
          
          # Check if evaluation was successful
          if [ "$status_code" -ge 200 ] && [ "$status_code" -lt 300 ]; then
            echo "✅ Agent evaluation started successfully!"
            eval_id=$(echo "$response_body" | jq -r '.evaluationId // .id // empty')
            if [ -n "$eval_id" ]; then
              echo "Evaluation ID: $eval_id"
              echo "📊 You can monitor the evaluation progress in your Airia dashboard"
            fi
          else
            echo "⚠️ Failed to start agent evaluation (promotion was still successful)"
            echo "Evaluation Status Code: $status_code"
            echo "Evaluation Response: $response_body"
          fi
        env:
          AIRIA_API_ENDPOINT: ${{ secrets.AIRIA_API_ENDPOINT }}
          AIRIA_EVALUATION_ENDPOINT: ${{ secrets.AIRIA_EVALUATION_ENDPOINT }}
